# fly.toml app configuration file generated for nekbestia2 on 2026-09-03T14:41:01Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nekbestia-proxy-gafan"
primary_region = "fra"

[http_service]
  internal_port = 7860
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[services]]
  protocol = "tcp"
  internal_port = 7860

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
