name: Sync Fork

on:
  schedule:
    - cron: '0 * * * *' # Controlla aggiornamenti ogni ora
  workflow_dispatch: # Permette di avviarlo a mano con un tasto

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necessario per scrivere i cambiamenti nel tuo repo
    steps:
      - name: Sync upstream changes
        uses: ahmadnassri/action-upstream-sync@v3
        with:
          upstream_repository: realbestia1/EasyProxy
          upstream_branch: main
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
